### ISSUE TITLE
ReferenceError: google is not defined 

### ISSUE THREAD

**Issue by HuyHoang-Ta** [JustFly1984/react-google-maps-api#1347]
## Please provide an explanation
- My app consists a **list of charts**
- Each chart has two types: **Line chart** and **Google Map chart**

## Your Environment

os: linux

node --version: 12.18.3

react version: 16.11.0

@react-google-maps/api version: ^1.9.12

## How is it behave?
- When I switch a chart from Google Map chart to Line chart, everything works fine as long as that chart is the **only** Google Map chart in the list
- When there are more than one Google Map charts present, I get the following error: **ReferenceError: google is not defined** 
- Here are screenshots of the error:
![Chart-Error1](https://user-images.githubusercontent.com/61722520/91269099-b6731380-e7a0-11ea-82a2-2bb7f693932f.png)
![Chart-Error2](https://user-images.githubusercontent.com/61722520/91269105-b96e0400-e7a0-11ea-96fe-d7c2d27a8369.png)

**Comment by JustFly1984** [comment]
@HuyHoang-Ta please provide minimal reproduction in codesandbox.io

**Comment by webraptor** [comment]
> @HuyHoang-Ta please provide minimal reproduction in codesandbox.io

Probably used one of the examples, [such as this one](https://react-google-maps-api-docs.netlify.app/#useloadscript), and copy pasted `google.maps.ControlPosition.RIGHT_CENTER`

**Comment by p45mark** [comment]
I'm having the same problem using NextJS. If I add any references to the `google` object, the site fast refreshes and looks fine. If I hard refresh the page (aka cmd+R or F5) I get this same error. I'm referencing `google` when creating an SVG to use as a Marker

```
 const mySvg = {
    path:
      'M20.2...',
    fillColor: '#003363',
    fillOpacity: 0.8,
    scale: 2,
    anchor: new google.maps.Point(10, 15)
  };
```

**Comment by p45mark** [comment]
Like @webraptor mentioned, I just copy/pasted the sample code from the docs and it's showing the error (even if I add my API key). 

[codesandbox with error](https://codesandbox.io/s/react-google-maps-api-6frh2?file=/src/App.js)

**Comment by p45mark** [comment]
Ah ok... I tracked this down by searching through Issues. The docs for that sample code [just need to be updated](https://github.com/JustFly1984/react-google-maps-api/issues/227#issuecomment-601162034)

**Comment by JustFly1984** [comment]
Currently having issues with docs deploy due to the bug in build tool tsdx. Originally we had webpack setup, but now we stuck with tsdx.

Maintainer of tsdx knows about the bug and currently in process of releasing new version with fix.

After deploy is fixed, new docs will have gradual update, and re-design.

I'm planing to create video tutorials to cover library in depth.

**Comment by JustFly1984** [comment]
Tsds is fixed, docs are redeployed.

**Comment by rakeshlanjewar** [comment]
I don't this I am currently doing 

`window.google.maps.ControlPosition.RIGHT_CENTER`

**Comment by mohdsauood** [comment]
i followed the docs but still cant use google inside useEffect hook . [here's the code](https://stackoverflow.com/questions/64775426/react-google-maps-api-google-is-not-defined-error-when-accessed-inside-useef?noredirect=1#comment114528847_64775426)
