### ISSUE TITLE
infowindows fire twice, one blank

### ISSUE THREAD

**Issue by Kiel-H-Byrne** [JustFly1984/react-google-maps-api#86]
# Please provide an explanation
i am trying to load an `InfoWindow` `onMouseOver` of a `Marker`. the `<InfoWindow>` component is a child of `<GoogleMap>`. when I hover over the marker, i get an InfoWindow. when i leave the marker, a smaller, empty infowindow still appears (it loaded behind the first one, which dissapeared `onMouseExit`) They stack up on every hover, and i have to manually "x" them out.

## Your Environment

os: mac
node --version v8.11.4
react version ^16.8.4",
(Created with create-react-app)

@react-google-maps/api version "^1.2.0"

## How is it behave?
two infowindows appear onMouseOver, one is blank.
one infowindow hides onMouseExit.
![Screen Shot 2019-04-07 at 10 49 51 PM](https://user-images.githubusercontent.com/955269/55696060-59977300-5989-11e9-9e4b-5a9fd4d4682f.png)
![Screen Shot 2019-04-07 at 11 03 53 PM](https://user-images.githubusercontent.com/955269/55696150-b004b180-5989-11e9-9c69-b20cf7f8dbe4.png)
(the BIGGER one is working correctly... the smaller one is the relic...)

## How should it behave correctly?
one InfoWindow should appear onMouseOver, one should hide onMouseExit

**Comment by uriklar** [comment]
Hi @tdotholla! Thanks for the bug report. Could you please provide a codesandbox reproduction?
Thanks

**Comment by tdotholla** [comment]
> codesandbox

Yes please see here: https://codesandbox.io/s/813npr9yo2

**Comment by uriklar** [comment]
Thanks. I'll check it out tomorrow

**Comment by uriklar** [comment]
@tdotholla I created a PR with the fix and we we'll publish 1.2.1 sometime later today. Thanks

**Comment by tdotholla** [comment]
That was fast! I appreciate it! Great work also

**Comment by JustFly1984** [comment]
@tdotholla I've published 1.2.1 version, please test.

**Comment by tdotholla** [comment]
This works ppuuurrrrfectly now. Thank yoU!

**Comment by thomasguillaux** [comment]
Hi! I still get the two InfoWindows shown up on the map... Am i the only one?

**Comment by adityabilawar** [comment]
same

**Comment by hafizMDM** [comment]
Any solution for this? 
Still same problem


<img width="278" alt="image" src="https://user-images.githubusercontent.com/2582410/143459991-8c02cb83-7e84-4d2b-b75c-0e59008eb5a0.png">

**Comment by ryma1738** [comment]
I am having this same problem...
![image](https://user-images.githubusercontent.com/51891293/144699556-3a6a469e-fa19-44cc-a833-93cb9c203ff7.png)

**Comment by enriquebarco** [comment]
Hey, I am also having a similar problem. Did someone ever find a solution?

**Comment by enriquebarco** [comment]
Hi All, 

I found a solution for the problem we were encountering above. You can work around this by removing react strict mode in the root index.js file in your react application. Hope this helps!

**Comment by weilin93** [comment]
I too having the same issue. Is there other way to solve this? 
I don't really want to remove strict mode.

**Comment by JustFly1984** [comment]
@weilin93 can you please fork my latest PR, and reproduce your issue in gatsby-example?

**Comment by JustFly1984** [comment]
@weilin93 I've released 2.10.1 - please ask to reopen if issue persist.

**Comment by weilin93** [comment]
Hey @JustFly1984, sorry was busy and did not do the gatsby-example.
So I reinstalled the package and the issue is still ther
![Screenshot 2022-04-29 at 15 04 15](https://user-images.githubusercontent.com/73017624/165950294-1f76593d-1e17-421c-b482-decf20fb315c.png)
e

**Comment by JustFly1984** [comment]
@weilin93 please provide minimal reproduction in codesandbox.io

**Comment by hramdas** [comment]
I used InfoWindowF and it solved this issue for me

**Comment by hugobiais** [comment]
The use of InfoWindowF instead of InfoWindow should be specified in the documentation (Because InfoWindowF is, to my knowledge, not findable in the documentation). 
This would save a lot of time to future developers encountering the same problem we all faced. 

[Here](https://codesandbox.io/s/react-google-maps-api-multiple-markers-infowindow-updated-dvv91k?file=/src/index.js) is an upaded version of a codesandbox version that implements the changes and works correctly with the current version of react-google-maps/api (2.18.1)

I'd love to help with the documentation changes for this if needed

**Comment by ADCJustinH** [comment]
using InfoWindowF 'solves' the problem but poorly. If your eyes are fast you will still see that the additional window renders and displays for a fraction of a second before going away. It's good enough for me for now but I do hope it gets fixed in the future.

**Comment by FediRouatbi** [comment]
> 

thanks this was helpful, the only way that worked for me

**Comment by FediRouatbi** [comment]
Thanks this was helpful, the only way that worked for me



> using InfoWindowF 'solves' the problem but poorly. If your eyes are fast you will still see that the additional window renders and displays for a fraction of a second before going away. It's good enough for me for now but I do hope it gets fixed in the future.

**Comment by Alkissourvinos** [comment]
> Hi All,
> 
> I found a solution for the problem we were encountering above. You can work around this by removing react strict mode in the root index.js file in your react application. Hope this helps!

This is the solution to the problem, everyone. Thank you, @enriquebarco, for the solution!
